### ISSUE TITLE
Error finding routes

### ISSUE THREAD

**Issue by nakkamarra** [desaroger/pm2-hooks#2]
Hello,

I'm having an issue getting the pm2-hooks default response to return a success when setting it up. I'm using nginx as a reverse proxy to the hook server and when I try to reach the url that I have set up for the hook, I get a "no route on url" response.

After going into my ecosystem file (usually processes.json, correct?), I found that my app wasn't named and added a name. I restarted the module and still have an error that the route specified cannot be found. Any idea what might be going on here? Could this be an nginx mix up or might it be something wrong with my config files?

Thanks in advance,

Nick

**Comment by desaroger** [comment]
Hi @nakkamarra ! Sorry, I was out of town and just read your message. Currently working, I will read carefully your message and give you more info.

**Comment by nakkamarra** [comment]
@desaroger Sorry, I forgot to update here. The issue is with the way that nginx routes paths. It seems that proxy_pass wasn't forwarding the path correctly, and on top of that 304 redirects from HTTP to HTTPS seemed to be giving me a bit of an issue when trying to pass data upstream. Worth checking out regardless, but you can close this. Thanks
