### ISSUE TITLE
Service Timeouts

### ISSUE THREAD

**Issue by Setherizor** [desaroger/pm2-hooks#7]
**pm2-hooks** seems to be working properly (running commands, outputting logs), but each time GitHub sends out webhook to it, the website (Github)  shows a nasty error message:

> "We couldn’t deliver this payload: Service Timeout"

Is this a configuration issue? Or expected behavior?

**Comment by desaroger** [comment]
Hi @Setherizor! Seems github can get to your server, I don't think this has nothing to do with the server itself!

I think you can test some things:
- It's your url correct? The url is something like this `http://{host}:{port}/{appName}`. Be sure you have the correct port, etc.
- Is the server running? if you open the url in your browser, you get the response, see the log, etc? Maybe you are behind a firewall? maybe your port is closed on your machine?
- It's the server accessible online? If you open the url from your phone, from another network (to discard issues with the dns and cache), it works?

**Comment by Setherizor** [comment]
That is what is so strange:

- the server is functioning and accessible
- the logs show activity and what I would expect from GitHub webhook payloads

Everything is functioning, **except** the status message from GitHub saying if the request went through.

**Comment by desaroger** [comment]
Mmm strange!

I just read github has a 10 seconds timeout for webhooks. Is your server answering in that time?
I just realized pm2-hooks waits until the command to end before returning the response, and I am pretty sure this is an issue, because in the command you can put some heavy duty work and it can be run for more than 10 seconds!

I will make a fix for that, maybe this solve your issue

**Comment by desaroger** [comment]
Hi @Setherizor, I just published the version v1.1.14 which (I hope) fixes your issue. The only difference is that now I don't wait the command to end, I return a response to the webhook as soon as possible.

I tested it with the old version, running the command `sleep 15s` and as expected github said "Service Timeout", but after updating pm2-hooks to the last version everything worked fine.

I hope this fixes your issue. Please let me know if everything works now or keeps failing. Thanks!

**Comment by Setherizor** [comment]
Everything is working wonderfully and GitHub is now showing green checks! Thank you for such a wonderful project!
