### ISSUE TITLE
secret code of GitHub

### ISSUE THREAD

**Issue by Productivix** [desaroger/pm2-hooks#8]
hi, 
good flexible package - .
What about the secret code (of GitHub) to avoid false requests ?

**Comment by Productivix** [comment]
never answers

**Comment by desaroger** [comment]
Hi! Sorry for taking so much time to answer, I had not noticed your first comment! Thanks for your words.

This library is in an early stage, tbh I got busy and was not able to work more with it. As part of the TODOs I had in mind was to check the github secret, but never got to do it. Sorry for the inconvenience.

I was thinking that could be cool to do an update to this project, I could update dependencies and just add the secret check. Let me try to find some free time and maybe I will do it. Remember that if you want to do a PR for that or other features it would be awesome too!

Thanks and sorry for the delayed response.
